services:
  db:
    image: mysql:latest
    container_name: mysql_R7
    environment:
      MYSQL_DATABASE: sistema_r7
      MYSQL_ROOT_PASSWORD: AujAC#8511Q5
      MYSQL_PASSWORD: AujAC#8511Q5
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - Sistema_R7

  app:
    build: .
    container_name: app
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: R7
      DB_USERNAME: root
      DB_PASSWORD: AujAC#8511Q5
    depends_on:
      - db
    tty: true
    networks:
      - Sistema_R7

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_R7
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: AujAC#8511Q5
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - Sistema_R7

networks:
  Sistema_R7:
    driver: bridge
